Deep-Consulting-Solutions/n8n-fork

docker/images/n8n-custom/Dockerfile

modified docker file

---

.github/workflows/ecr-deploy.yml

added packages read permission

---

docker/images/n8n-custom/Dockerfile

udated dockerfile for custom build

---

docker/images/n8n-custom/Dockerfile

added DB_TYPE env

---

docker/images/n8n-custom/Dockerfile

modified Dockerfile

---

packages/workflow/src/NodeHelpers.ts

adds argument default value true

AA12341 - n8n remove auto generated id from webhook urls

---

packages/editor-ui/src/components/SwaggerEditor/SwaggerEditor.vue

added checks to prevent editor overiding webhook node values

---

packages/cli/src/ActiveWorkflowRunner.ts
packages/cli/src/TestWebhooks.ts

remove hashtag and querystring which might be added for openapi/swagger

fix: remove hashtag and querystring which might be added for openapi/swagger

---

.gitignore
packages/cli/src/ActiveWorkflowRunner.ts
packages/cli/src/TestWebhooks.ts

adds httpMethod to condition and updates gitignore

fix: add httpMethod to condition and update gitignore

---

README.md
packages/cli/src/elitesoftwareautomation/utils.ts
packages/nodes-base/nodes/Webhook/Webhook.node.ts
packages/nodes-base/nodes/Webhook/authentication/index.ts

1) corrects webhook node portal auth logic
2) updates readme
3) cleanup other codes

fix: correct auth logic, update readme and cleanup code

---

packages/editor-ui/package.json
packages/editor-ui/src/components/ParameterInputList.vue
packages/editor-ui/src/components/SendGridPreview/SendGridPreview.vue
packages/editor-ui/src/components/SwaggerEditor/SwaggerEditor.vue
packages/workflow/src/Interfaces.ts
pnpm-lock.yaml

feat(sendgridpreview.vue): add preview parameter

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts

Add Authorization Role Validation Option

---

packages/editor-ui/package.json
packages/editor-ui/src/components/SendGridPreview/SendGridPreview.vue
pnpm-lock.yaml

feat(sendgridpreview.vue): replace @sendgrid/client with basic fetch

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts
packages/nodes-base/nodes/Webhook/authentication/index.ts

#AA-10722/AA-12484 Fix auth related issues 

---

packages/nodes-base/nodes/NocoDbHttpRequest/GenericFunctions.ts
packages/nodes-base/nodes/NocoDbHttpRequest/NocoDbHttpRequest.node.json
packages/nodes-base/nodes/NocoDbHttpRequest/NocoDbHttpRequest.node.ts
packages/nodes-base/nodes/NocoDbHttpRequest/V1/NocoDbHttpRequestV1.node.ts
packages/nodes-base/nodes/NocoDbHttpRequest/V2/NocoDbHttpRequestV2.node.ts
packages/nodes-base/nodes/NocoDbHttpRequest/V3/NocoDbHttpRequestV3.node.ts
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/NocoDbHttpRequest.test.ts
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/workflow.delete.json
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/workflow.get.json
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/workflow.patch.json
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/workflow.post.json
packages/nodes-base/nodes/NocoDbHttpRequest/test/node/workflow.put.json
packages/nodes-base/nodes/NocoDbHttpRequest/test/utils/utils.test.ts
packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.ts
packages/nodes-base/package.json

feat(nocodbhttprequest): add nocodb http request node

---

packages/nodes-base/nodes/NocoDbHttpRequest/V3/NocoDbHttpRequestV3.node.ts

fix(nocodbhttprequestv3.node.ts): update env variable names

---

packages/nodes-base/nodes/NocoDbHttpRequest/V3/NocoDbHttpRequestV3.node.ts

fix: use correct env variable for request token

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts

Add validation for NocoDB Webhook

be/aa-12452. Add NocoDB Webhook auth option

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts

1) output authData from webhook node
2) ensure security by removing sensitive details from output itemData

feat: output authData and ensure security

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts

renames webhook output item authData property

refactor: rename webhook output item authData property

---

packages/cli/src/AbstractServer.ts

add allowed headers cors

---

packages/nodes-base/nodes/Webhook/Webhook.node.ts

reference component schemas openapi validation

---

packages/cli/package.json
packages/cli/src/AbstractServer.ts
packages/cli/src/Server.ts
packages/cli/src/databases/entities/DataRecoveryActivity.ts
packages/cli/src/databases/entities/GenericEntity.ts
packages/cli/src/databases/entities/ServerIncident.ts
packages/cli/src/databases/entities/index.ts
packages/cli/src/databases/migrations/postgresdb/1689942863738-addIncidentHandlingTables.ts
packages/cli/src/databases/migrations/postgresdb/index.ts
packages/cli/src/databases/migrations/sqlite/1689942863738-addIncidentHandlingTables.ts
packages/cli/src/databases/migrations/sqlite/index.ts
packages/cli/src/lib/incidentLogger/index.ts
packages/cli/src/posthog/index.ts
packages/cli/src/reusables/index.ts

Add Incident Handling for listening to workflow failures

be/aa-12751. Add Incident Handling

---

pnpm-lock.yaml

be/aa-12751. Update lock file

---

packages/cli/src/lib/incidentLogger/index.ts
packages/cli/src/posthog/index.ts

Fix issue to log incident in dev + staging envs

be/aa-12751. QA Fix

---

packages/cli/src/lib/incidentLogger/index.ts
packages/cli/src/reusables/index.ts

be/aa-12751. Fix typescript bug

---

packages/cli/src/reusables/index.ts

Add Project Name to Desk Ticket

be/aa-12751. Add project name

---

packages/cli/src/WorkflowRunnerProcess.ts
packages/cli/src/lib/incidentLogger/index.ts
packages/cli/src/posthog/index.ts

QA Request to catch error from Schedule Trigger

be/aa-12751. QA Request

---

packages/cli/src/WorkflowRunnerProcess.ts
packages/cli/src/lib/incidentLogger/index.ts

be/aa-12751. Add debug logs

---

packages/cli/src/WorkflowExecuteAdditionalData.ts
packages/cli/src/WorkflowRunner.ts
packages/cli/src/WorkflowRunnerProcess.ts
packages/cli/src/commands/worker.ts

be/aa-12751. Add debug logs 2

---

packages/cli/src/WorkflowRunner.ts
packages/cli/src/WorkflowRunnerProcess.ts
packages/cli/src/lib/incidentLogger/index.ts

be/aa-12751. QA Fix 2

---

packages/cli/src/lib/incidentLogger/index.ts
packages/cli/src/reusables/index.ts

changed variable for accountsUrl in incident handling
